### ISSUE TITLE
wording around damage tokens

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#231]
These are wound tokens
damage is about dealing damage. not the same

**Comment by 5H4Z** [comment]
This would likely need significant revisions to do one of the following:
1. Rename the damage tokens themselves and then update all effects and tests regarding those tokens
2. Change all the messages regarding specifically placing, moving or removing those tokens to use the word wounds instead of damage (probably by using a variable to pass into the function would be easiest)

In any case, it would also require confirming against card text across a wide range of cards.
