### ISSUE TITLE
Swift Messenger on my turn took my main action away

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#723]
Swift Messenger on my turn took my main action away (SBN) - played as a reaction to a salamander dying and monk spirit entering play, while an accelerate was in operation (extra side actions). Only weird things about it AFAIK

**Comment by 5H4Z** [comment]
Replicated: 
![image](https://user-images.githubusercontent.com/89332227/135690014-63d3056f-87d4-44d4-911d-b31d55628dfe.png)

**Comment by 5H4Z** [comment]
This is occurring because the play action on Swift Messenger has ignoreActionCost, but this only affects whether it meets requirements, it doesn't change the actual cost of playing the action. I've created a test that currently fails for confirming when the main action is not used up: https://github.com/5H4Z/ashteki/tree/bug-swift-messenger

**Comment by 5H4Z** [comment]
In baseability.js, resolveCosts does not apply the filtering that occurs in canPayCosts
