### ISSUE TITLE
More squall stallion rins Fury fun

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#766]
I attacked a Squall Stallion with my own Stallion, and my opponent reacted with Rins Fury.  The damage was not prevented - my Stallion was not able to be targeted and destroyed which I think is correct, but seems like the damage should still be prevented, right?

**Comment by 5H4Z** [comment]
Actually it is worse than that. When I tested this, my Squall Stallion (as the Rin's Fury player) ended up being destroyed, presumably by my Rin's Fury. I chose not to counter and my Stallion would only have received 1 damage and it had 4 life due to Ice Buff: 
![image](https://user-images.githubusercontent.com/89332227/137800722-d9006614-3c30-48d2-ba2b-54e9f50ef370.png)
